CommandSet GondorFoundationCommandSet
   1  = Command_ConstructGondorFarm
   2 = Command_ConstructGondorBlackSmith
   3  = Command_ConstructGondorBarracks
   4  = Command_ConstructGondorArcherRange
   5  = Command_ConstructGondorStable
   6  = Command_ConstructGondorWorkshop
   7  = Command_ConstructGondorBattleTower
   8  = Command_ConstructGondorWell
   9 = Command_ConstructGondorStatue
   10 = Command_ConstructGondorMarketPlace
   11 = Command_ConstructGondorStoneMaker
End
CommandSet GondorFoundationCommandSet_NoMarketPlace
   1  = Command_ConstructGondorFarm
   2 = Command_ConstructGondorBlackSmith
   3  = Command_ConstructGondorBarracks
   4  = Command_ConstructGondorArcherRange
   5  = Command_ConstructGondorStable
   6  = Command_ConstructGondorWorkshop
   7  = Command_ConstructGondorBattleTower
   8  = Command_ConstructGondorWell
   9 = Command_ConstructGondorStatue
   10 = Command_ConstructGondorMarketPlace_Disabled
   11 = Command_ConstructGondorStoneMaker
End
CommandSet GondorFoundationCommandSet_Osgiliath
   1  = Command_ConstructGondorFarm
   2  = Command_ConstructGondorBlackSmith
   3  = Command_ConstructGondorBarracks
   4  = Command_ConstructGondorArcherRange
   5  = Command_ConstructGondorWorkshop
   6  = Command_ConstructGondorWell
   7  = Command_ConstructGondorStatue
   8  = Command_ConstructGondorMarketPlace
End
CommandSet GondorFoundation_IndependantCommandSet
	1  = Command_ConstructGondorFarm
	2  = Command_ConstructGondorBlackSmith
	3  = Command_ConstructGondorBarracks
	4  = Command_ConstructGondorArcherRange
	5  = Command_ConstructGondorStatue
	6  = Command_ConstructGondorWell
	7  = Command_ConstructGondorBattleTower
	8  = Command_ConstructGondorStable
	9  = Command_ConstructGondorWorkshop
	11 = Command_ConstructGondorMarketPlace
End
CommandSet GondorFoundationCommandSetUpgradedEntMoot
	1  = Command_ConstructGondorFarm
	2  = Command_ConstructGondorBlackSmith
	3  = Command_ConstructGondorBarracks
	4  = Command_ConstructGondorArcherRange
	5  = Command_ConstructGondorStatue
	6  = Command_ConstructGondorWell
	7  = Command_ConstructGondorBattleTower
	8  = Command_ConstructGondorStable
	9  = Command_ConstructGondorWorkshop
	10 = Command_ConstructGondorStoneMaker
	11 = Command_ConstructGondorMarketPlace
	12 = Command_ConstructEntMoot
End
CommandSet GondorBaseDefenceFoundationCommandSet
	1 = Command_ConstructGondorSentryTower
End
CommandSet RohanBaseDefenceFoundationCommandSet
	1 = Command_ConstructRohanSentryTower
End
CommandSet MordorBaseDefenceFoundationCommandSet
	1 = Command_ConstructEvilSentryTower
End
CommandSet IsengardBaseDefenceFoundationCommandSet
	1 = Command_ConstructEvilSentryTower
End
CommandSet NeutralBattleTowerCommandSet
	1 = Command_ExitGarrison
End
CommandSet GondorWallFoundationCommandSet
  1  = Command_ConstructGondorWall
End
CommandSet RohanFoundationCommandSet
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanWindmill
  3  = Command_ConstructRohanBarracksFoundation
  4  = Command_ConstructRohanArcherRange
  5  = Command_ConstructRohanStable
  6  = Command_ConstructRohanWorkshop
  7  = Command_ConstructRohanBattleTower
  8  = Command_ConstructRohanDraftTower
  9  = Command_ConstructRohanStatue
  10  = Command_ConstructRohanWell
End
CommandSet RohanFoundationCommandSet_Eaves
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanWindmill
  3  = Command_ConstructRohanStatue
  4  = Command_ConstructRohanWell
End
CommandSet RohanFoundationCommandSet_Westfold
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanWindmill
  3  = Command_ConstructRohanBarracksFoundation
  4  = Command_ConstructRohanArcherRange
  5  = Command_ConstructRohanStable
  6  = Command_ConstructRohanBattleTower
  7  = Command_ConstructRohanDraftTower
  8  = Command_ConstructRohanStatue
  9  = Command_ConstructRohanWell
End
CommandSet RohanFoundationCommandSetUpgradedEntMoot
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanArcherRange
  3  = Command_ConstructRohanStable
  4  = Command_ConstructRohanArmory
  5  = Command_ConstructEntMoot
End
CommandSet RohanWallFoundationCommandSet
  1  = Command_ConstructRohanWall
End
CommandSet MordorFoundationCommandSet
    1  = Command_ConstructMordorSlaughterHouse
	2  = Command_ConstructMordorArmory
	3  = Command_ConstructMordorLumberMill
	4  = Command_ConstructMordorOrcPit
	5  = Command_ConstructMordorHaradrimPalace
	6  = Command_ConstructMordorTrollCage
	7  = Command_ConstructMordorSiegeWorks
	8  = Command_ConstructMumakilPen
	9  = Command_constructMordorBattleTower
End
CommandSet IsengardFoundationCommandSet
    1  = Command_ConstructIsengardFurnace
	2  = Command_ConstructIsengardLumberMill
	3  = Command_ConstructIsengardUrukPit
	4  = Command_ConstructIsengardTavern
	5  = Command_ConstructIsengardWargPit
	6  = Command_ConstructIsengardSiegeWorks
	7  = Command_ConstructIsengardBattleTower
	8  = Command_ConstructIsengardWargSentry
	9  = Command_ConstructIsengardArmory
End
CommandSet WildFoundationCommandSet
   	1  = Command_ConstructWildMineShaft
	2  = Command_ConstructWildLumberMill
	3  = Command_ConstructWildTreasureTrove
	4  = Command_ConstructWildLodge
	5  = Command_ConstructWildCave
	6  = Command_ConstructWildSpiderPit
	7  = Command_ConstructWildFissure	
	8  = Command_ConstructWyrmLair
	9  = Command_ConstructWildSentryTower
End
CommandSet ElvenFoundationCommandSet  
   1  = Command_FoundationConstructElvenMallornTree
   2  = Command_FoundationConstructEregionForge 
   3  =	Command_FoundationConstructElvenBarracks
   4  = Command_FoundationConstructElvenGreenPasture
   5  =	Command_FoundationConstructElvenEntMoot
   6  = Command_FoundationConstructElvenWatchTower
   7  =	Command_FoundationConstructElvenMirrorOfGaladriel
   8  = Command_FoundationConstructElvenStatue
End
CommandSet ElvenFoundationCommandSet_NoMirror
   1  = Command_FoundationConstructElvenMallornTree
   2  = Command_FoundationConstructEregionForge 
   3  =	Command_FoundationConstructElvenBarracks
   4  = Command_FoundationConstructElvenGreenPasture
   5  =	Command_FoundationConstructElvenEntMoot
   6  = Command_FoundationConstructElvenWatchTower
   7  =	Command_FoundationConstructElvenMirrorOfGaladriel_Disabled
   8  = Command_FoundationConstructElvenStatue
End
CommandSet ElvenFoundationCommandSet_Lothlorien
   1  = Command_FoundationConstructElvenMallornTree
   2  = Command_FoundationConstructEregionForge 
   3  =	Command_FoundationConstructElvenBarracks
   4  = Command_FoundationConstructElvenStatue
End
CommandSet DwarvenFoundationCommandSet
End
CommandSet DwarvenFoundationUpgradedCommandSet  
   1  = Command_FoundationConstructDwarvenMineShaft
   2  = Command_FoundationDwarvenEreborForge
   3  =	Command_FoundationConstructDwarvenBarracks
   4  = Command_FoundationConstructDwarvenAssembly
   5  = Command_FoundationConstructDwarvenForgeWorks
   6  = Command_FoundationConstructDwarvenWorkshop
   7  = Command_FoundationConstructDwarvenSentryTower
   8  = Command_FoundationConstructDwarvenWell
   9  = Command_FoundationConstructDwarvenStatue
End
CommandSet EntFoundationCommandSet
  1  = Command_ConstructEntMoot
End
CommandSet RivendellFoundationCommandSet
	1  = Command_ConstructRivendellOrchard
	2  = Command_ConstructRivendellForge
	3  = Command_ConstructRivendellBreelandCamp
	4  = Command_ConstructRivendellDunedainGathering
	5  = Command_ConstructRivendellDormitory
	6  = Command_ConstructRivendellLibrary
	7  = Command_ConstructRivendellSentryTower
	8  = Command_ConstructRivendellWell
	9  = Command_ConstructRivendellStatue
End
CommandSet RivendellFoundationCommandSet_NoLibrary
	1  = Command_ConstructRivendellOrchard
	2  = Command_ConstructRivendellForge
	3  = Command_ConstructRivendellBreelandCamp
	4  = Command_ConstructRivendellDunedainGathering
	5  = Command_ConstructRivendellDormitory
	6  = Command_ConstructRivendellLibrary_Disabled
	7  = Command_ConstructRivendellSentryTower
	8  = Command_ConstructRivendellWell
	9  = Command_ConstructRivendellStatue
End
CommandSet AotRRushFoundationCommandSet
   1  = Command_FoundationConstructLorienFletTD
   2  = Command_FoundationConstructGondorBarracksTD
   3  = Command_FoundationConstructEreborSiegeTD
End
CommandSet GuldurFoundationCommandSet
   	1  = Command_ConstructGuldurSlaveMill
	2  = Command_ConstructGuldurFountOfCorruption
	3  = Command_ConstructGuldurGuldurGaol
	4  = Command_ConstructGuldurSpiderLair
	5  = Command_ConstructGuldurSorceryTower
	6  = Command_ConstructGuldurRuinousTower
	7  = Command_ConstructGuldurRestlessBarrow
End
CommandSet GuldurFoundationCommandSet_DE
   	1  = Command_ConstructGuldurSlaveMill_DE
	2  = Command_ConstructGuldurFountOfCorruption_DE
	3  = Command_ConstructGuldurGuldurGaol_DE
	4  = Command_ConstructGuldurSpiderLair_DE
	5  = Command_ConstructGuldurSorceryTower_DE
	6  = Command_ConstructGuldurRuinousTower_DE
	7  = Command_ConstructGuldurRestlessBarrow_DE
End
CommandSet MirkwoodFoundationCommandSet
	1  = Command_ConstructMirkwoodHuntingLodgeFoundation
	2  = Command_ConstructMirkwoodVineyardFoundation
	3  = Command_ConstructMirkwoodTrainingGroundsFoundation
	4  = Command_ConstructMirkwoodBeorningCabinFoundation
	5  = Command_ConstructMirkwoodRoyalBarracksFoundation
	6  = Command_ConstructMirkwoodTreasuryFoundation
	7  = Command_ConstructMirkwoodSiegeGroundsFoundation
	8  = Command_ConstructMirkwoodCellarDoorFoundation
	9  = Command_ConstructMirkwoodBattleTowerFoundation
	10 = Command_ConstructMirkwoodWellFoundation
	11 = Command_ConstructMirkwoodStatueFoundation
End