;-----------------------------------------------------------------------------------------------
;-----------------------------Rivendell----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = GandalfSummon
		Texture        = scgandalfsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = OldManWillowSummon
		Texture        = scoldmanwillow
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End   
	RadiusCursorTemplate = ArnorRuinRadiusCursor
		Texture        = SCArnorRuin
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = BamfurlongRadiusCursor
		Texture        = SCBamfurlong
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End  
  RadiusCursorTemplate = HallOfFireRadiusCursor
		Texture        = SCHOFSummon
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = SongOfSpringRadiusCursor
		Texture        = scspringsong
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = ArwenTinuvielRadiusCursor
		Texture        = SCTinuviel
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End    
  RadiusCursorTemplate = ArwenEvenstarRadiusCursor
		Texture        = scevenstar
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End   
  RadiusCursorTemplate = GlorfindelAmanRadiusCursor
		Texture        = sclightaman
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End  
  RadiusCursorTemplate = ElrondHomelyHouseRadiusCursor
		Texture        = schomelyhouse
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = ElrondRingOfAirRadiusCursor
		Texture        = scvilya
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End 
  RadiusCursorTemplate = AkallabethCursor
		Texture        = screvakall
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = TangadoHaidCursor
		Texture        = sctangadohaid
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End    
;-----------------------------------------------------------------------------------------------
;-----------------------------Erebor----------------------------------------------
;-----------------------------------------------------------------------------------------------	
	RadiusCursorTemplate = IronHillsSummon
		Texture        = scIHsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	
	RadiusCursorTemplate = KhazadDumSummon
		Texture        = scmoriasummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	
	RadiusCursorTemplate = ThorinProphecy
		Texture        = scprophecy
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	
	RadiusCursorTemplate = WyrmSlayersRunes
		Texture        = scrunesoffire
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = EreborHorn
		Texture        = scereborhorn
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = BardRabbleRouser
		Texture        = scrabblerouser
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = ThrorsHoard
		Texture        = scthrorshoard
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = EreborUnkindness
		Texture        = scunkindness
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = EreborFullyArmedandFilthy
		Texture        = scfilthy
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MasterSpyCursor
		Texture        = scmasterspy
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
		RadiusCursorTemplate = SecretWaysGloinCursor
		Texture        = scsecretways
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Lorien----------------------------------------------
;-----------------------------------------------------------------------------------------------	
	RadiusCursorTemplate = RingOfAdamant
		Texture        = scringofadamant
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MirkwoodSummon
		Texture        = scmirksummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GoNoFurther
		Texture        = scnofurther
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = NandorTreasure
		Texture        = scossiriand
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MallornGrove
		Texture        = scmallorngrove
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = ElvenHorn
		Texture        = sclorienhorn
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = RadagastSummon
		Texture        = scradagastsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = CelebornWisdom
		Texture        = scwisebeyond
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Gondor----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = DenethorFavor
		Texture        = scstewardfavor
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = DenethorHighAuthority
		Texture        = schighauthority
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = GondorWhiteTree
		Texture        = scwhitetree
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GondorLoneTower
		Texture        = scgondortower
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = IthilienGardenRadiusCursor
		Texture        = scithiliengarden
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End 
	RadiusCursorTemplate = PrepareForBattleCursor
		Texture        = scprepareforbattle
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = NumenorEngineeringCursor
		Texture        = scnumengi
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MordorChallengeCursor
		Texture        = scmordorchallenge
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = CaptainHornCursor
		Texture        = sccapthorn
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = LandsKeptSafeCursor
		Texture        = sclandskeptsafe
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCBoromirWarcry
		Texture        = scBoromir_WarCry
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCFaramirQuality
		Texture        = scFaramir_Quality
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End	
;-----------------------------------------------------------------------------------------------
;-----------------------------Rohan----------------------------------------------
;-----------------------------------------------------------------------------------------------	
	RadiusCursorTemplate = OathOfCirionRadiusCursor
		Texture        = SCOathOfCirion
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = EverholtBoarRadiusCursor
		Texture        = SCBoarSummon
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	   Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End  
  RadiusCursorTemplate = StormcrowRadiusCursor
		Texture        = SCStormcrow
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = WestfoldHornRadiusCursor
		Texture        = scwestfoldhorn
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = MarkHelmRadiusCursor
		Texture        = scmarkhelm
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = MarkFrecaRadiusCursor
		Texture        = scmarkfreca
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = PukelSummonRadiusCursor
		Texture        = scpukelsummon
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End   
  RadiusCursorTemplate = PukelFaithfulRadiusCursor
		Texture        = scpukelfaithful
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End 
  RadiusCursorTemplate = PukelPathsRadiusCursor
		Texture        = scpukelpaths
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End 
  RadiusCursorTemplate = PukelStoneSkinRadiusCursor
		Texture        = scpukelskin
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End   
   RadiusCursorTemplate = SurrenderArmsRadiusCursor
 	Texture        = scsurrenderarms
    	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
    	OpacityMax     = 60%
    	OpacityThrobTime  = 1000
    	Color          = R:255 G:255 B:255 A:255
    	OnlyVisibleToOwningPlayer = Yes
  End  
;-----------------------------------------------------------------------------------------------
;-----------------------------Misty Mountains----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = DrumsInTheDeep
		Texture        = scdrumsdeep
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = UrshakIntimidation
		Texture        = scintimidation
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = FireDrakeStrikeRadiusCursor
		Texture        = SCCDragonStrike
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1500
		Color          = R:255 G:255 B:255 A:128
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = AngmarCitadelRadiusCursor
		Texture        = scangmarruin
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1500
		Color          = R:255 G:255 B:255 A:128
		OnlyVisibleToOwningPlayer = Yes
	End	
   RadiusCursorTemplate = BlackPitRadiusCursor
 	Texture        = scblackpit
    	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
    	OpacityMax     = 60%
    	OpacityThrobTime  = 1000
    	Color          = R:255 G:255 B:255 A:255
    	OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = WyrmSummonRadiusCursor
	Texture        = SCCCallOfTheDeep
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 20%
    OpacityMax     = 60%
    OpacityThrobTime  = 1000
    Color          = R:255 G:255 B:255 A:255
    OnlyVisibleToOwningPlayer = Yes
  End  
  RadiusCursorTemplate = SCBolgSummon
		Texture        = scbolgsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
End
RadiusCursorTemplate = SCFrozenWasteNew
		Texture        = scfrozenwastenew
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
End
;-----------------------------------------------------------------------------------------------
;-----------------------------Mordor----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = WitchKingsHour
		Texture        = scmyhour
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MoSBaradDur
		Texture        = scmouthbarad
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MoSSorcery
		Texture        = scmouthsorcery
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MoSCursed
		Texture        = scmouthcursed
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MordorEyeSymbol
		Texture        = scmordoreye
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
;-----------------------------------------------------------------------------------------------
;-----------------------------Isengard----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = IsenWhiteHand
		Texture        = scwhitehand
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Guldur----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = SCGuldurEnsnare
		Texture        = scensnare
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurCarnage
		Texture        = sccarnage
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurFollowLights
		Texture        = scfollowlights
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCGuldurChill
		Texture        = scgravechill
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurWither
		Texture        = scwither
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurGift
		Texture        = scnecrogift
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurForestFear
		Texture        = scforestfear
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCGuldurBlackWarg
		Texture        = scblackwargs
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurHysteria
		Texture        = schysteria
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = SCGuldurConcealment
		Texture        = scconcealment
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCGuldurGwanthaur
		Texture        = scgwanthaur
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = SCGuldurDeadTroll
		Texture        = scdeadtroll
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End			
	RadiusCursorTemplate = GuldurEncasingWebs
		Texture        = scencasingwebs
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurWebOfLies
		Texture        = scweboflies
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurDeepRot
		Texture        = scdeeprot
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = GuldurWitheringTouch
		Texture        = scwitheringtouch
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurToxicBile
		Texture        = scbile
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
;		Color          = R:47 G:144 B:111 A:255
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurRestlessBones
		Texture        = sccrestlessbones
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurGwanthaurReclamation
		Texture        = screclamation
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurGwanthaurExpulsion
		Texture        = scexpulsion
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurGwanthaurSoulTrap
		Texture        = scsoultrap
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = CargastSpellsBarrowCursor
		Texture        = scspellbarrows
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = KrimpulDungeonMasterCursor
		Texture        = scdungeonmaster
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurParasiticEmbraceCursor
		Texture        = scpembrace
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = GuldurDarkMemoriesCursor
		Texture        = scdarkmemories
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	;-----------------------------------------------------------------------------------------------
;-----------------------------Mirkwood----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = SCHornGate
		Texture        = schorngate
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCHiddenSentry
		Texture        = schiddensentry
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCElvesAwokeThem
		Texture        = scelvesawokethem
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
		RadiusCursorTemplate = SCElvenkingRoad
		Texture        = scelvenkingsroad
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCElvenkingFeast
		Texture        = scelvenkingsfeast
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCElvenkingPatience
		Texture        = scelvenkingspatience
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCSpearsofFramsburg
		Texture        = scspearsframsburg
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCNoneMayEnter
		Texture        = scelvenkingsdecree
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCLoveSilverJewels
		Texture        = scsilverjewels
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCSoundtheAlarm
		Texture        = scsoundalarm
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCFeast
		Texture        = scfeast
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCOrcWarVeteran
		Texture        = scorcwarveteran
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCEyesAndEars
		Texture        = sceyesandears
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCDorwinionRed
		Texture        = scdorwinionred
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBadBatch
		Texture        = scbadbatch
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCPrinceWoodland
		Texture        = scprinceofwoodlandrealm
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	 RadiusCursorTemplate = StopRightThereCursor
 	Texture        = scstoprightthere
    	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
    	OpacityMax     = 60%
    	OpacityThrobTime  = 1000
    	Color          = R:255 G:255 B:255 A:255
    	OnlyVisibleToOwningPlayer = Yes
  End  
  	RadiusCursorTemplate = SCSacredOak
		Texture        = scsacredoak
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	 RadiusCursorTemplate = SCWaystoneTeleport
		Texture        = scroadteleport
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCWardingStones
		Texture        = scstone1
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBlessingAldaron
		Texture        = scblessingaldaron
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCWhiteStag
		Texture        = scwhitestag
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
    RadiusCursorTemplate = SCFeyWisdom
		Texture        = scfeywisdom
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGreatHunt
		Texture        = scgreathunt
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
    RadiusCursorTemplate = SCPrisonGuardStop
		Texture        = scprisonguardstop
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	 RadiusCursorTemplate = SCHuntingSnare
		Texture        = scsnare
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBardingSummon
		Texture        = scbardingsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCRedAxe
		Texture        = scredaxe
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCStoneHewer
		Texture        = scstonehewer
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCMarkThrush
		Texture        = scmarkthrush
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCRangerCraft
		Texture        = scrangercraft
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCMightyVeteran
		Texture        = scmightyveteran
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCWisdomYore
		Texture        = scwisdomofyore
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCStopRightThereLaketown
		Texture        = scstoprighttherelaketown
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCStopRightThereLaketown2
		Texture        = scstoprighttherelaketown2
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
  ;-----------------------------------------------------------------------------------------------
;-----------------------------Haradwaith----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = SCForthMenofDarkness
		Texture        = scforthmenofdarkness
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCKhandishCharioteers
		Texture        = sckhandishcharioteers
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCDrySpell
		Texture        = scdryspell
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCCurseWindDemon
		Texture        = scwinddemon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
		RadiusCursorTemplate = SCOasis
		Texture        = scoasis
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End