Upgrade Upgrade_TDGoodMeleeBanners
	Type              = OBJECT
	BuildCost		= 150
	BuildTime		= 0
End
Upgrade Upgrade_TDGoodMeleeBlades
	Type              = OBJECT
	BuildCost		= 200
	BuildTime		= 0
	ResearchSound	= UpgradeForgedBlades
	UpgradeFX		= FX_PorterDeliverForgedBlades
End
Upgrade Upgrade_TDGoodMeleeArmor
	Type              = OBJECT
	BuildCost		= 200
	BuildTime		= 0
	ResearchSound	= UpgradeHeavyArmor
	UpgradeFX		= FX_PorterDeliverHeavyArmor
End

Upgrade Upgrade_TDStructureRank2
	Type              = OBJECT
	BuildCost		= 300
	BuildTime		= 0
End

Upgrade Upgrade_TDStructureRank3
	Type              = OBJECT
	BuildCost		= 400
	BuildTime		= 0
End

Upgrade Upgrade_TDStructureRank4A
	Type              = OBJECT
	BuildCost		= 500
	BuildTime		= 0
End

Upgrade Upgrade_TDStructureRank4B
	Type              = OBJECT
	BuildCost		= 500
	BuildTime		= 0
End

Upgrade Upgrade_PurchaseNumenTreb
	Type			= OBJECT
	BuildCost		= 1200
	BuildTime		= 30
	DisplayName		= Upgrade:ReplacementWeapon
End


; Upgrade Upgrade_PlantShield
  ; Type               = OBJECT
  ; BuildTime          = 0.0
  ; BuildCost          = 0
; End 
; Upgrade Upgrade_RaiseShield
  ; Type               = OBJECT
  ; BuildTime          = 0.0
  ; BuildCost          = 0
; End
; Upgrade Upgrade_ElvesBetterStealth
  ; DisplayName       = UPGRADE:ElfStealthUpgrade
  ; Type              = OBJECT
  ; ButtonImage       = SCGrabPassenger
  ; Cursor			= WeaponUpgrade
  ; UnitSpecificSound = NoSound // GondorPorterVoiceCreateFlame
; End
; Upgrade Upgrade_RohanHorseBow
	; DisplayName       = UPGRADE:RohanHorseBow
	; Type              = OBJECT
	; ButtonImage       = BuildingNoArt
	; Cursor			= WeaponUpgrade
	; //UnitSpecificSound = GondorPorterVoiceCreate__________
; End
; Upgrade Upgrade_RohanHorseLance
	; DisplayName       = UPGRADE:RohanHorseLance
	; Type              = OBJECT
	; ButtonImage       = BuildingNoArt
	; Cursor			= WeaponUpgrade
	; //UnitSpecificSound = GondorPorterVoiceCreate__________
; End
; Upgrade Upgrade_RohanHornsOfTheRohirrim
	; DisplayName       = UPGRADE:RohanHornsOfTheRohirrim
	; Type              = OBJECT
	; ButtonImage       = BuildingNoArt
	; Cursor			= WeaponUpgrade
	; //UnitSpecificSound = GondorPorterVoiceCreate__________
; End
; Upgrade Upgrade_GondorCounterweights
	; DisplayName       = UPGRADE:GondorCounterweights
	; Type              = OBJECT
	; Cursor			= ArrowUpgrade
	; //UnitSpecificSound = GondorPorterVoiceCreate__________
; End
; Upgrade Upgrade_KnightShield
  ; DisplayName       = UPGRADE:KnightShield
  ; Tooltip		= TOOLTIP:GondorKnightShields
  ; Type              = OBJECT
  ; ButtonImage       = SCGrabPassenger
  ; Cursor			= ArmorUpgrade
; End
; Upgrade Upgrade_GandalfBlast
  ; Type		    = OBJECT
; End
; Upgrade Upgrade_GandalfLightningSword
  ; Type              = OBJECT
; End
; Upgrade Upgrade_GandalfWordOfPower
  ; Type              = OBJECT
; End
; Upgrade Upgrade_GandalfLeadership
  ; Type              = OBJECT
; End
; Upgrade Upgrade_ElrondLeadership
  ; Type				= OBJECT
; End
; Upgrade Upgrade_ElrondFarsight
  ; Type				= OBJECT
; End
; Upgrade Upgrade_ElrondTornado
  ; Type				= OBJECT
; End
; Upgrade Upgrade_ElrondRestoration
  ; Type				= OBJECT
; End
; Upgrade Upgrade_TomBombadilLeadership
  ; Type              = OBJECT
; End
; Upgrade Upgrade_DainLeadership
  ; Type              = OBJECT
; End
; Upgrade Upgrade_DainBarukKhazad
  ; Type				= OBJECT
; End
; Upgrade Upgrade_DainRoyalGuard
  ; Type				= OBJECT
; End
; Upgrade Upgrade_DainMightyRage
  ; Type				= OBJECT
; End
; Upgrade Upgrade_TheodenLeadership
  ; Type              = OBJECT
; End
; Upgrade Upgrade_TheodenKingsFavor
  ; Type              = OBJECT
; End
; Upgrade Upgrade_TheodenGloriousCharge
	; Type			= OBJECT
; End
; Upgrade Upgrade_DarkGlory
	; Type			= OBJECT
; End
; Upgrade Upgrade_EnableSpecialAbilityAngmarMorgramirRuin
	; Type			= OBJECT
; End
; Upgrade Upgrade_HwaldarSummons1
  ; Type				= OBJECT
; End
; Upgrade Upgrade_HwaldarSummons2
  ; Type				= OBJECT
; End
; Upgrade Upgrade_AzogBrigandage
  ; Type				= OBJECT
; End
; Upgrade Upgrade_AzogFury
  ; Type 				= OBJECT
; End
; Upgrade Upgrade_AzogCracktheWhip
  ; Type				= OBJECT
; End
; Upgrade Upgrade_SharkuBloodHunt
	; Type			= OBJECT
; End
; Upgrade Upgrade_GandalfIstariLight
  ; Type				= OBJECT
 ; End
; Upgrade Upgrade_SarumanFireBall
  ; Type              = OBJECT
; End
; Upgrade Upgrade_SarumanThunderBolt
  ; Type              = OBJECT
; End
; Upgrade Upgrade_WormtongueVenomousWords
  ; Type				= OBJECT
; End
; Upgrade Upgrade_WormtongueBackstab
  ; Type				= OBJECT
; End
; Upgrade Upgrade_WormtongueCorrodeAllegiance
  ; Type				= OBJECT
; End
; Upgrade Upgrade_ThranduilThornofVengeance
  ; Type              = OBJECT
; End
; Upgrade Upgrade_ThranduilDeadeye
  ; Type              = OBJECT
; End
; Upgrade Upgrade_ThranduilMoveUnseen
  ; Type              = OBJECT
; End
; Upgrade Upgrade_ThranduilElfCloak
  ; Type              = OBJECT
; End
; Upgrade Upgrade_SarumanDominate
  ; Type              = OBJECT
; End
; Upgrade Upgrade_SharkuTameTheBeast
  ; Type              = OBJECT
; End
; Upgrade Upgrade_SarumanSpeechCraft
  ; Type              = OBJECT
; End
; Upgrade Upgrade_MumakilLevel1
  ; Type              = OBJECT
; End
; Upgrade Upgrade_MumakilLevel2
  ; Type              = OBJECT
; End
; Upgrade Upgrade_MountainTrollVeterancy
  ; Type              = OBJECT
; End
; Upgrade Upgrade_Shadowfax
	; Type			= OBJECT
; End
; Upgrade Upgrade_GimliLeapTrigger
	; Type			= OBJECT
; End
; Upgrade Upgrade_RogashLeapTrigger
	; Type			= OBJECT
; End
; Upgrade Upgrade_RogashRageoftheNorth
	; Type			= OBJECT
; End
; Upgrade Upgrade_GimliSlayerTrigger
	; Type			= OBJECT
; End
; Upgrade Upgrade_GimliAxeThrow
  ; Type              = OBJECT
; End
; Upgrade Upgrade_GimliFreeLife
  ; Type              = OBJECT
; End
; Upgrade Upgrade_AragornLeadership
  ; Type				= OBJECT
; End
; Upgrade Upgrade_AragornElendil
  ; Type              = OBJECT
; End
; Upgrade Upgrade_AragornBladeMaster
  ; Type              = OBJECT
; End
; Upgrade Upgrade_GlorfindelBladeOfPurity
  ; Type              = OBJECT
; End
; Upgrade Upgrade_GlorfindelWindRider
  ; Type				= OBJECT
; End
; Upgrade Upgrade_GlorindelStarlight
  ; Type				= OBJECT
; End
; Upgrade Upgrade_LurtzCarnage
  ; Type              = OBJECT
; End
; Upgrade Upgrade_AragornOathbreakers
  ; Type              = OBJECT
; End
; Upgrade Upgrade_EomerOutlawLeader
  ; Type              = OBJECT
; End
; Upgrade Upgrade_HwaldarBrigandLeader
  ; Type              = OBJECT
; End
; Upgrade Upgrade_SharkuManEater
  ; Type              = OBJECT
; End
; Upgrade Upgrade_EomerSpear
  ; Type				= OBJECT
 ; End
; Upgrade Upgrade_LurtzPillage
  ; Type              = OBJECT
; End
; Upgrade Upgrade_WitchKingLeadership
  ; Type				= OBJECT
; End
; Upgrade Upgrade_DreadVisage
  ; Type				= OBJECT
; End
; Upgrade Upgrade_DreadWrath
  ; Type				= OBJECT
; End
; Upgrade Upgrade_Screech
  ; Type				= OBJECT
; End
; Upgrade Upgrade_HourOfTheWitchKing
  ; Type				= OBJECT
; End
; Upgrade Upgrade_HourOfTheWitchKingMorgulSorceryTimer
 	; Type				= OBJECT
	; BuildTime			= 3333.0
	; BuildCost			= 0.0
; End
; Upgrade Upgrade_MouthOfSauronDoubt
  ; Type				= OBJECT
; End
; Upgrade Upgrade_MouthOfSauronDissent
  ; Type				= OBJECT
; End
; Upgrade Upgrade_MouthOfSauronEvilEye
  ; Type				= OBJECT
; End
; Upgrade Upgrade_GothmogDayoftheOrc
  ; Type				= OBJECT
; End
; Upgrade Upgrade_GothmogIronHand
  ; Type				= OBJECT
; End
; Upgrade Upgrade_GothmogCarnage
  ; Type              		= OBJECT
; End
; Upgrade Upgrade_EomerHorseLordLeader
	; Type			= OBJECT
; End
; Upgrade Upgrade_BoromirHornOfGondor
  ; Type              = OBJECT
; End
; Upgrade Upgrade_BoromirForGondorSpeech
  ; Type              = OBJECT
; End
; Upgrade Upgrade_BoromirLastStand
  ; Type              = OBJECT
; End
; Upgrade Upgrade_DamrodLeadership
  ; Type              = OBJECT
; End
; Upgrade Upgrade_DamrodRallyRangers
  ; Type              = OBJECT
; End
; Upgrade Upgrade_DamrodDeadlySniper
  ; Type              = OBJECT
; End
; Upgrade Upgrade_LegolasKnifeFighter
  ; Type              = OBJECT
; End
; Upgrade Upgrade_LegolasTrainArchers
  ; Type              = OBJECT
; End
; Upgrade Upgrade_LegolasArrowWind
  ; Type              = OBJECT
; End
; Upgrade Upgrade_LurtzCrippleTrigger
	; Type			= OBJECT
; End
; Upgrade Upgrade_EowynSmiteTrigger
	; Type			= OBJECT
; End
; Upgrade Upgrade_EowynDisguiseTrigger
	; Type			= OBJECT
; End
; Upgrade Upgrade_ArwenFloodTrigger
	; Type = OBJECT
; End
; Upgrade Upgrade_ArwenElvenGraceTrigger
	; Type = OBJECT
; End
; Upgrade Upgrade_HaldirLeadership
	; Type			= OBJECT
; End
; Upgrade Upgrade_HaldirGoldenArrow
	; Type			= OBJECT
; End
; Upgrade Upgrade_EowynShieldMaiden
	; Type			= OBJECT
; End
; Upgrade Upgrade_MountEowyn
	; Type			= OBJECT
; End
; Upgrade Upgrade_LurtzLeadership
  ; Type              = OBJECT
; End
; Upgrade Upgrade_LurtzRampage
	; Type			= OBJECT
; End
; Upgrade Upgrade_LurtzStealth
	; Type			= OBJECT
; End
; Upgrade Upgrade_PorterGOLD
	; Type			= OBJECT
; End
; Upgrade Upgrade_FaramirLeadership
  ; Type              = OBJECT
; End
; Upgrade Upgrade_FaramirWoundingArrow
  ; Type              = OBJECT
; End
; Upgrade Upgrade_FaramirKnightRangerToggle
  ; Type              = OBJECT
; End
; Upgrade Upgrade_FaramirWarSpeech
  ; Type              = OBJECT
; End
; Upgrade Upgrade_FaramirCaptainOfGondor
  ; Type              = OBJECT
; End
; Upgrade Upgrade_EnableDwarvenGloinSlam
  ; Type              = OBJECT
; End
; Upgrade Upgrade_EnableDwarvenGloinShakeFoundation
  ; Type              = OBJECT
; End
; Upgrade Upgrade_EnableGloinSmash
  ; Type              = OBJECT
; End
; Upgrade Upgrade_InfantryCaptureBuilding
	; DisplayName		= UPGRADE:InfantryCaptureBuilding
	; Type			= OBJECT
; End
; Upgrade Upgrade_WitchkingMorgulBlade
	; Type			= OBJECT
; End
; Upgrade Upgrade_WhisperofDeathTrigger
	; Type			= OBJECT
; End
; Upgrade Upgrade_BlinkTrigger
	; Type			= OBJECT
; End
;////--------------------------------------------------------------
; //----NOTE: These technology upgrades are no longer needed because with the Men of the West
; //----We are useing the Gondor Technologies
; //---- ROHAN ---------------------------------------------------------------------
; Upgrade Upgrade_TechnologyRohanBasicTraining
	; DisplayName       = UPGRADE:RohanBasicTraining
	; Type              = PLAYER
	; BuildCost		= ROHAN_TECH_BASIC_TRAINING_BUILDCOST
	; BuildTime		= ROHAN_TECH_BASIC_TRAINING_BUILDTIME
	; ResearchCompleteEvaEvent	= UpgradeBannerCarrierTechnologyReady		//RohanBannerVoiceSalute
; End
; Upgrade Upgrade_TechnologyRohanFireArrows
	; DisplayName       = UPGRADE:RohanFireArrowUpgrade
	; Type              = PLAYER
	; BuildCost		= ROHAN_TECH_FIRE_ARROWS_BUILDCOST
	; BuildTime		= ROHAN_TECH_FIRE_ARROWS_BUILDTIME
	; ResearchCompleteEvaEvent	= UpgradeFlameArrowsReady
	; SkirmishAIHeuristic = AI_UPGRADEHEURISTIC_IMPORTANT
; End
; //-------------------
; Upgrade Upgrade_TechnologyRohanForgedBlades
	; DisplayName       = UPGRADE:RohanForgedBlades
	; Type              = PLAYER
	; BuildCost		= ROHAN_TECH_FORGED_BLADES_BUILDCOST
	; BuildTime		= ROHAN_TECH_FORGED_BLADES_BUILDTIME
	; ResearchCompleteEvaEvent	= UpgradeForgedBladesReady
; End
; Upgrade Upgrade_RohanForgedBlades
	; DisplayName       = UPGRADE:RohanForgedBlades
	; Type              = OBJECT
	; //Tooltip		= TOOLTIP:RohanForgedBlades
	; BuildCost		= ROHAN_PERSONAL_FORGED_BLADES_BUILDCOST
	; BuildTime		= ROHAN_PERSONAL_FORGED_BLADES_BUILDTIME
	; ResearchSound	= UpgradeForgedBlades
	; UpgradeFX		= FX_PorterDeliverForgedBlades
	; SubUpgradeTemplateNames = Upgrade_RohanForgedBladesForPeasants Upgrade_RohanForgedBladesForElves //Upgrade_RohanForgedBlades 
; End
; Upgrade Upgrade_RohanForgedBladesForPeasants
	; DisplayName       = UPGRADE:RohanForgedBlades
	; Type              = OBJECT
	; //Tooltip		= TOOLTIP:RohanForgedBlades
	; BuildCost		= ROHAN_PERSONAL_FORGED_BLADES_BUILDCOST
	; BuildTime		= ROHAN_PERSONAL_FORGED_BLADES_BUILDTIME
	; ResearchSound	= UpgradeForgedBlades
	; UpgradeFX		= FX_PorterDeliverForgedBlades
; End
; Upgrade Upgrade_RohanForgedBladesForElves
	; DisplayName       = UPGRADE:RohanForgedBlades
	; Type              = OBJECT
	; //Tooltip		= TOOLTIP:RohanForgedBlades
	; BuildCost		= ROHAN_PERSONAL_FORGED_BLADES_BUILDCOST
	; BuildTime		= ROHAN_PERSONAL_FORGED_BLADES_BUILDTIME
	; ResearchSound	= UpgradeForgedBlades
	; UpgradeFX		= FX_PorterDeliverForgedBlades
; End
; //-------------------
; Upgrade Upgrade_TechnologyRohanHeavyArmor
	; DisplayName       = UPGRADE:RohanHeavyArmor
	; Type              = PLAYER
	; BuildCost		= ROHAN_TECH_HEAVY_ARMOR_BUILDCOST
	; BuildTime		= ROHAN_TECH_HEAVY_ARMOR_BUILDTIME
	; ResearchCompleteEvaEvent	= UpgradeHeavyArmorReady
; End
; Upgrade Upgrade_RohanHeavyArmor
	; DisplayName       = UPGRADE:RohanHeavyArmor
	; Type              = OBJECT
	; //Tooltip		= TOOLTIP:RohanHeavyArmor
	; BuildCost		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDCOST
	; BuildTime		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDTIME
	; ResearchSound	= UpgradeHeavyArmor
	; UpgradeFX		= FX_PorterDeliverHeavyArmor
	; ButtonImage       = BRArmory_HeavyArmor
	; Cursor			= ArmorUpgrade
	; SubUpgradeTemplateNames = Upgrade_RohanHeavyArmorForRohirrimArchers Upgrade_RohanHeavyArmorForElves Upgrade_RohanHeavyArmorForArchers Upgrade_RohanHeavyArmorForPeasants //Upgrade_RohanHeavyArmorForRohirrim
; End
; Upgrade Upgrade_RohanHeavyArmorForRohirrimArchers
	; DisplayName       = UPGRADE:RohanHeavyArmor
	; Type              = OBJECT
	; //Tooltip		= TOOLTIP:RohanHeavyArmor
	; BuildCost		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDCOST
	; BuildTime		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDTIME
	; ResearchSound	= UpgradeHeavyArmor
	; UpgradeFX		= FX_PorterDeliverHeavyArmor
	; ButtonImage       = BRArmory_HeavyArmor
	; Cursor			= ArmorUpgrade
; End
; Upgrade Upgrade_RohanHeavyArmorForElves
	; DisplayName       = UPGRADE:RohanHeavyArmor
	; Type              = OBJECT
	; //Tooltip		= TOOLTIP:RohanHeavyArmor
	; BuildCost		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDCOST
	; BuildTime		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDTIME
	; ResearchSound	= UpgradeHeavyArmor
	; UpgradeFX		= FX_PorterDeliverHeavyArmor
	; ButtonImage       = BRArmory_HeavyArmor
	; Cursor			= ArmorUpgrade
; End
; Upgrade Upgrade_RohanHeavyArmorForArchers
	; DisplayName       = UPGRADE:RohanHeavyArmor
	; Type              = OBJECT
	; //Tooltip		= TOOLTIP:RohanHeavyArmor
	; BuildCost		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDCOST
	; BuildTime		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDTIME
	; ResearchSound	= UpgradeHeavyArmor
	; UpgradeFX		= FX_PorterDeliverHeavyArmor
	; ButtonImage       = BRArmory_HeavyArmor
	; Cursor			= ArmorUpgrade
; End
; Upgrade Upgrade_RohanHeavyArmorForPeasants
	; DisplayName       = UPGRADE:RohanHeavyArmor
	; Type              = OBJECT
	; //Tooltip		= TOOLTIP:RohanHeavyArmor
	; BuildCost		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDCOST
	; BuildTime		= ROHAN_PERSONAL_HEAVY_ARMOR_BUILDTIME
	; ResearchSound	= UpgradeHeavyArmor
	; UpgradeFX		= FX_PorterDeliverHeavyArmor
	; ButtonImage       = BRArmory_HeavyArmor
	; Cursor			= ArmorUpgrade
; End
; //-------------------
; Upgrade Upgrade_TechnologyRohanHorseShield
	; DisplayName       = UPGRADE:RohanHorseShield
	; Type              = PLAYER
	; BuildCost		= ROHAN_TECH_HORSE_SHIELD_BUILDCOST
	; BuildTime		= ROHAN_TECH_HORSE_SHIELD_BUILDTIME
	; ResearchCompleteEvaEvent	= UpgradeHorseShieldsReady
; End
; ////--------------------------------------------------------------
; ////------Men of the West (Used to be rohon)----------------------
; ////--------------------------------------------------------------
; ////unit is now men of the west so useing gondor info
; Upgrade Upgrade_RohanBasicTraining
	; DisplayName			= UPGRADE:GondorBasicTraining
	; Type				= OBJECT
	; Tooltip				= UPGRADE:GondorBasicTraining
	; BuildCost			= 100;GONDOR_PERSONAL_BASIC_TRAINING_BUILDCOST
	; BuildTime			= GONDOR_PERSONAL_BASIC_TRAINING_BUILDTIME
	; ResearchCompleteEvaEvent		= UpgradeBannerCarrierReady
	; ;RequiredObjectFilter = NONE +GondorForge
	; StrategicIcon		= AptStrategicUnitUpgradeBannerCarrier
; End
; Upgrade Upgrade_RohanFireArrows
	; DisplayName       = UPGRADE:GondorFireArrowUpgrade
	; Type              = OBJECT
	; Tooltip			= TOOLTIP:GondorFlamingArrows
	; BuildCost		= GONDOR_PERSONAL_FIRE_ARROWS_BUILDCOST
	; BuildTime		= GONDOR_PERSONAL_FIRE_ARROWS_BUILDTIME
	; ResearchSound	= UpgradeFlamingArrows
	; UpgradeFX		= FX_PorterDeliverFlamingArrows
	; ;RequiredObjectFilter = ANY +GondorArcherRange +GondorForbiddenPool
	; StrategicIcon	= AptStrategicUnitUpgradeArrow
; End
; Upgrade Upgrade_RohanForgedBlades
	; DisplayName       = UPGRADE:GondorForgedBlades
	; Type              = OBJECT
	; Tooltip			= TOOLTIP:GondorForgedBlades
	; BuildCost		= GONDOR_PERSONAL_FORGED_BLADES_BUILDCOST
	; BuildTime		= GONDOR_PERSONAL_FORGED_BLADES_BUILDTIME
	; ResearchSound	= UpgradeForgedBlades
	; UpgradeFX		= FX_PorterDeliverForgedBlades
	; ;RequiredObjectFilter = NONE +GondorForge
	; StrategicIcon	= AptStrategicUnitUpgradeBlade
; End
; Upgrade Upgrade_RohanHeavyArmorForRohirrim
	; DisplayName       = UPGRADE:GondorHeavyArmor
	; Type              = OBJECT
	; Tooltip			= TOOLTIP:GondorHeavyArmor
	; BuildCost		= GONDOR_PERSONAL_HEAVY_ARMOR_BUILDCOST
	; BuildTime		= GONDOR_PERSONAL_HEAVY_ARMOR_BUILDTIME
	; ResearchSound	= UpgradeHeavyArmor
	; UpgradeFX		= FX_PorterDeliverHeavyArmor
	; ButtonImage     = BRArmory_HeavyArmor
	; Cursor			= ArmorUpgrade
	; ;RequiredObjectFilter = NONE +GondorForge
	; StrategicIcon	= AptStrategicUnitUpgradeArmor
; End
; Upgrade Upgrade_RohanHorseShield
	; DisplayName       = UPGRADE:GondorKnightShield
	; Type              = OBJECT
	; Tooltip			  = TOOLTIP:GondorKnightShields
	; BuildCost		  = GONDOR_PERSONAL_KNIGHT_SHIELD_BUILDCOST
	; BuildTime	      = GONDOR_PERSONAL_KNIGHT_SHIELD_BUILDTIME
	; ResearchSound	  = UpgradeHeavyArmor
	; UpgradeFX		  = FX_PorterDeliverHorseShields
	; ;RequiredObjectFilter = NONE +GondorStable
	; StrategicIcon	= AptStrategicUnitUpgradeHorseShield
; End